### ISSUE TITLE
Security exception filling user roles

### ISSUE THREAD

**Issue by fullergalway** [floragunncom/search-guard-authbackend-ldap#4]
Possibly a doPrivileged block missing...
* dlic-search-guard-authbackend-ldap-2.4-7.jar
* search-guard-2-2.4.4.11.jar

```
[DEBUG][com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend] Unable to fill user roles due to
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1528)
        at java.lang.Thread.getContextClassLoader(Thread.java:1443)
        at org.ldaptive.provider.jndi.JndiConnectionFactory.createInternal(JndiConnectionFactory.java:79)
        at org.ldaptive.provider.jndi.JndiConnectionFactory.createInternal(JndiConnectionFactory.java:20)
        at org.ldaptive.provider.AbstractProviderConnectionFactory.create(AbstractProviderConnectionFactory.java:87)
        at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:267)
        at org.ldaptive.referral.AbstractReferralHandler.followReferral(AbstractReferralHandler.java:158)
        at org.ldaptive.referral.AbstractReferralHandler.handle(AbstractReferralHandler.java:193)
        at org.ldaptive.AbstractOperation.execute(AbstractOperation.java:146)
        at com.floragunn.dlic.auth.ldap.util.LdapHelper.search(LdapHelper.java:44)
        at com.floragunn.dlic.auth.ldap.backend.LDAPAuthenticationBackend.exists(LDAPAuthenticationBackend.java:170)
        at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:334)
```

Contents of plugin-security.policy are the not modified original.
```
grant {
  permission java.lang.RuntimePermission "shutdownHooks";
  permission java.lang.RuntimePermission "getClassLoader";
  permission java.lang.RuntimePermission "setContextClassLoader";
  permission javax.security.auth.AuthPermission "modifyPrivateCredentials";
  permission javax.security.auth.AuthPermission "doAs";
  permission javax.security.auth.kerberos.ServicePermission "*","accept";
  permission java.lang.RuntimePermission "accessDeclaredMembers";
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
}
```
To replicate try using the internal database for authentication, and ldap for authorization.

**Comment by fullergalway** [comment]
This problem went away by itself after getting ldap configured correctly.

For any others encountering this problem, suggestion is to use ldap for authc and authz before switching to a different authc.
